### ISSUE TITLE
Would you mind do a new release? 

### ISSUE THREAD

**Issue by yongheekim-dev** [fredo-dedup/JSONSchema.jl#22]
Well it's just warning message, but My teammates are complaining about null error. Also not converting `OrderedDict` to `Dict` would make my code simpler

**Comment by odow** [comment]
@JuliaRegistrator register()

**Comment by odow** [comment]
I meant to do this last week, but forgot. Please feel free to ping me earlier next time.

**Comment by yongheekim-dev** [comment]
It wasn't urgent. Thank you! 😄
