### ISSUE TITLE
replace path with JSONPointer.jl? 

### ISSUE THREAD

**Issue by YongHee-Kim** [fredo-dedup/JSONSchema.jl#25]
I have developed [JSONPointer](https://github.com/devsisters/JSONPointer.jl) for the nested data structure. 
It seems to me JSONShcema.jl could be benefited by using JSONPointer.jl as backend. 

https://github.com/fredo-dedup/JSONSchema.jl/blob/86dcf6d67934f744ceacfd8cb042ed3011d09a9b/src/schema.jl#L32-L58

**Comment by odow** [comment]
Yes, that could be a good idea. I don't really understand the current implementation. 

Is JSONPointer registered and stable? If not, another option is just to copy the `pointer.jl` file and tests into `JSONSchema` to minimize dependencies for the near-term, and then switch once things are ironed out.

**Comment by YongHee-Kim** [comment]
JSONPointer is registered and I think it's stable. (although there seems to be no one using it other than me...) it's function is simple enough and I will make test coverage 100% soon. 
But as you suggested I will copy `pointer.jl` to`JSONSchema` and work on PR first. 🙂
