### ISSUE TITLE
Order of arguments for `validate` is unexpected

### ISSUE THREAD

**Issue by helgee** [fredo-dedup/JSONSchema.jl#31]
IMHO the argument order of `validate` differs from idiomatic Julia style.

The "fixed" argument (what would be the object instance in a single dispatch language, e.g. `schema.validate(data)`) is usually put first, e.g. `push!(array, 1)` or `print(io, "something")`. Thus, I feel that `validate(schema, data)` would be more idiomatic than `validate(data, schema)`.

Not a big deal but I get it wrong everytime the way it is 🙈

**Comment by odow** [comment]
Feel free to open a PR with the alternate order.
