### ISSUE TITLE
Upgrade HTTP.jl dependency to 1.0.x

### ISSUE THREAD

**Issue by ndortega** [fredo-dedup/JSONSchema.jl#39]

**Comment by ndortega** [comment]
Thanks Oscar!

 I honestly wasn't expecting you to close out this issue this fast, I appreciate it. This library is a transitive dependency and was preventing me from upgrading my HTTP.jl version to 1.0 without breaking the integration between my library and SwaggerMarkdown.jl (which depends on your package).

I'm planning on adding this to [Oxygen.jl](https://github.com/ndortega/Oxygen.jl) to validate incoming  & outgoing json.

**Comment by odow** [comment]
> I'm planning on adding this to [Oxygen.jl](https://github.com/ndortega/Oxygen.jl) to validate incoming & outgoing json.

Nice. @fredo-dedup isn't very active anymore, but I have commit access. Let me know if you encounter any issues. I use this in JuMP to validate some models, so I haven't really tested it in production beyond our quite specific use-case.

**Comment by ndortega** [comment]
Thanks @odow, I'll make sure to keep you in the loop
