### ISSUE TITLE
`additionalProperties` improper treatment

### ISSUE THREAD

**Issue by algunion** [fredo-dedup/JSONSchema.jl#61]
The [`additionalProperties`](https://json-schema.org/understanding-json-schema/reference/object#additionalproperties) directive seems to undergo validation like being a member inside the _properties_ object.

Would a PR on this issue be welcomed? Or is there a specific reason for the current behavior, and would you like it to stay as it is?

**Later edit**: actually, this is part of `draft 7`.  So you just went incremental here and haven't yet reached this piece. Anyway, is there some work in progress to pass the Drat 7 tests? (I ask because I can help, but at the same time, I am not attracted to duplicated work).

**Comment by odow** [comment]
PRs to improve things are most welcome! I'm not working on anything at the moment, so no risk of duplicated work :smile:
