### ISSUE TITLE
JuliaRegistrator

### ISSUE THREAD

**Issue by odow** [fredo-dedup/JSONSchema.jl#9]
Hey @fredo-dedup two extra things we need:

1) Can you install JuliaRegistrator: https://github.com/JuliaRegistries/Registrator.jl#install-registrator

2) And can you install TagBot by clicking on the "Configure" button:
https://github.com/apps/julia-tagbot

Thanks

**Comment by fredo-dedup** [comment]
Done.

**Comment by odow** [comment]
Thanks!
